site_name: solutions-provider
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/JPZOD/solutions-provider
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/JPZOD">JPZOD</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
